openapi: 3.0.1
info:
  title: WSO2_Demo_API
  description: API Definition of WSO2_Demo_API
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2-demo
paths:
  /insert:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /fetch:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /update:
    put:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /delete:
    delete:
      responses:
        default:
          description: Default response
